openapi: '3.0.2'
info:
  title: Traveler app
  version: '0.1.0'
servers:
  - url: https://api.server.test/v1

tags:
- name: "Authentication"

paths:
  /users:
    get:
      tags:
      - "pet"
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  
  /user/d:
    get:
      tags:
      - "pet"
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
    